{% set name = "pipefunc" %}
{% set version = "0.41.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pipefunc-{{ version }}.tar.gz
  sha256: 71683fab72b9f57efa533a5be7544b179dca1b2a8810322dc45b9b4dbd288dbf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - wheel
    - versioningit
    - pip
  run:
    - python >={{ python_min }}
    - networkx
    - psutil
    - cloudpickle
    - numpy

test:
  imports:
    - pipefunc
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pipefunc/pipefunc
  summary: A Python library for defining, managing, and executing function pipelines.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
