{% set name = "pipefunc" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pipefunc-{{ version }}.tar.gz
  sha256: c3fe2eb7dda36583dff4ee68e85f81d2cbb6e219a329aef6797361903b22ea03

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - versioningit
    - pip
  run:
    - python >=3.8
    - networkx
    - psutil
    - versioningit
    - typing-extensions
    - cloudpickle
    - numpy
    - tabulate


test:
  imports:
    - pipefunc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/basnijholt/pipefunc
  summary: A Python library for defining, managing, and executing function pipelines.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
