{% set name = "pipefunc" %}
{% set version = "0.48.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pipefunc-{{ version }}.tar.gz
  sha256: 37df92e7b232edf6e48c42d9d1e8366e8692c4784c79d2c0eb7a651ca349fdb7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - wheel
    - versioningit
    - pip
  run:
    - python >={{ python_min }}
    - networkx
    - psutil
    - cloudpickle
    - numpy

test:
  imports:
    - pipefunc
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pipefunc/pipefunc
  summary: A Python library for defining, managing, and executing function pipelines.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
