{% set name = "pipefunc" %}
{% set version = "0.23.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pipefunc-{{ version }}.tar.gz
  sha256: 24d1fcd3ed2c8d5eb619f4907bb8da6e5f5541a0b635c1afd2b5662aca749c3e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - wheel
    - versioningit
    - pip
  run:
    - python >=3.10
    - networkx
    - psutil
    - cloudpickle
    - numpy

test:
  imports:
    - pipefunc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pipefunc/pipefunc
  summary: A Python library for defining, managing, and executing function pipelines.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
