{% set name = "pipefunc" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pipefunc-{{ version }}.tar.gz
  sha256: 5bbdda47a67ff6c043d1237ce3b28a8d5a6c732c3d3d3e8ab66e1bc499ed31cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - versioningit
    - pip
  run:
    - python >=3.8
    - networkx
    - psutil
    - versioningit
    - typing-extensions
    - cloudpickle

test:
  imports:
    - pipefunc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/basnijholt/pipefunc
  summary: A Python library for defining, managing, and executing function pipelines.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
