{% set name = "pipefunc" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pipefunc-{{ version }}.tar.gz
  sha256: c1ac3cd50e73662d368df05de0a8ccb81b6b14671d5251097f81340d01b0d73d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - versioningit
    - pip
  run:
    - python >=3.8
    - networkx
    - psutil
    - versioningit
    - typing-extensions
    - cloudpickle

test:
  imports:
    - pipefunc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/basnijholt/pipefunc
  summary: A Python library for defining, managing, and executing function pipelines.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
