{% set name = "pipefunc" %}
{% set version = "0.51.3" %}
{% set python_min = "3.10" %}

# handle undefined PYTHON in `noarch: generic` outputs
{% set PYTHON = PYTHON | default("$PYTHON") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pipefunc-{{ version }}.tar.gz
  sha256: 47abecc2dbd009b6ba3b4cf447ac7dbfab107587c07b43ec9f157db1120cfedd

build:
  noarch: python
  number: 0

outputs:
  - name: {{ name }}
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv
    requirements:
      host:
        - python {{ python_min }}
        - hatchling
        - wheel
        - versioningit
        - pip
      run:
        - python >={{ python_min }}
        - networkx
        - psutil  # technically not a requirement
        - cloudpickle
        - numpy
    test:
      imports:
        - pipefunc
      commands:
        - pip check
      requires:
        - pip
        - python {{ python_min }}

  - name: {{ name }}-extras
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
        - adaptive
        - graphviz
        - graphviz-anywidget
        - griffe
        - ipywidgets
        - matplotlib-base
        - pandas
        - psutil
        - rich
        - xarray
        - zarr
    test:
      imports:
        - pipefunc
      requires:
        - pip
        - python {{ python_min }}

about:
  home: https://github.com/pipefunc/pipefunc
  summary: A Python library for defining, managing, and executing function pipelines.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
