{% set name = "pipefunc" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pipefunc-{{ version }}.tar.gz
  sha256: 6d2602ca226f11a7cd42b0d946b3a824ae1de0c6f425b3c856385b741ab044d7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - versioningit
    - pip
  run:
    - python >=3.8
    - networkx
    - psutil
    - versioningit
    - typing-extensions
    - cloudpickle
    - numpy
    - tabulate


test:
  imports:
    - pipefunc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/basnijholt/pipefunc
  summary: A Python library for defining, managing, and executing function pipelines.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
